"""Root package for documenter2docset.

Convert Julia package documentation generated by Documenter.jl to Dash-compatible docset.
"""

__author__ = 'Jared Lumpe'
__email__ = 'mjlumpe@gmail.com'
__version__ = '0.1'
