"""Work with documentation generated by Documenter.jl."""

import ast


def read_search_index(fh):
	"""Read search_index.js.

	Can't part strictly as JSON  (even after removing the variable assignment
	at the beginning because it isn't formatted correctly (comma after last
	element of array). Use ast.literal_eval instead because it should match
	Python dict/list literal syntax.
	"""

	start = 'var documenterSearchIndex = '

	if fh.read(len(start)) != start:
		raise ValueError('Failed to parse search index')

	rest = fh.read()

	data = ast.literal_eval(rest)

	return data['docs']
